import Head from 'next/head'
import TeamHours from '../components/TeamHours'
import CalculationResult from '../components/CalculationResult'
import Footer from '../components/Footer'
import { CalculationProvider } from '../hooks/useHourCalculator'

const Home = () => {
  return (
    <>
      <Head>
        <title>Next Man Hour Calculator App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <CalculationProvider>
        <main className="min-h-screen bg-primary-900 px-14 py-16 flex flex-col items-center gap-12">
          <span className='font-bold text-3xl text-primary-50'>Man Hour Calculator</span>
          <div className='flex flex-col lg:flex-row gap-10'>
            <TeamHours/>
            <CalculationResult/>
          </div>
        </main>
      </CalculationProvider>

      <Footer/>
    </>
  )
}

export default Home